apiVersion: v1
kind: Service
metadata:
  name: mywebapp
spec:
  selector:
    app: mywebapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000       # The port on which the Service is exposed inside the cluster
      targetPort: 5000 # The port on which the Pod is listening
      nodePort: 30007  # The static port on each Node's IP address (optional, if omitted, a random port in the range 30000-32767 will be assigned)
