apiVersion: v1
kind: Service
metadata:
  name: testmywebapp
  namespace: default
  labels:
    app: mywebapp
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: mywebapp
  type: LoadBalancer

