apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: users-pod-lister
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: cloudera
  apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: ClusterRole
  name: pod-lister-cluster
  apiGroup: rbac.authorization.k8s.io
